// <auto-generated />
using FindSimilarServices.Fingerprinting.SQLiteDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FindSimilarServices.Migrations
{
    [DbContext(typeof(SQLiteDbContext))]
    [Migration("20180823181107_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("FindSimilarServices.Fingerprinting.SQLiteDb.Models.SubFingerprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Clusters");

                    b.Property<int>("HashTable0");

                    b.Property<int>("HashTable1");

                    b.Property<int>("HashTable10");

                    b.Property<int>("HashTable11");

                    b.Property<int>("HashTable12");

                    b.Property<int>("HashTable13");

                    b.Property<int>("HashTable14");

                    b.Property<int>("HashTable15");

                    b.Property<int>("HashTable16");

                    b.Property<int>("HashTable17");

                    b.Property<int>("HashTable18");

                    b.Property<int>("HashTable19");

                    b.Property<int>("HashTable2");

                    b.Property<int>("HashTable20");

                    b.Property<int>("HashTable21");

                    b.Property<int>("HashTable22");

                    b.Property<int>("HashTable23");

                    b.Property<int>("HashTable24");

                    b.Property<int>("HashTable3");

                    b.Property<int>("HashTable4");

                    b.Property<int>("HashTable5");

                    b.Property<int>("HashTable6");

                    b.Property<int>("HashTable7");

                    b.Property<int>("HashTable8");

                    b.Property<int>("HashTable9");

                    b.Property<float>("SequenceAt");

                    b.Property<int>("SequenceNumber");

                    b.Property<int>("TrackId");

                    b.HasKey("Id");

                    b.HasIndex("TrackId", "HashTable0", "HashTable1", "HashTable2", "HashTable3", "HashTable4", "HashTable5", "HashTable6", "HashTable7", "HashTable8", "HashTable9", "HashTable10", "HashTable11", "HashTable12", "HashTable13", "HashTable14", "HashTable15", "HashTable16", "HashTable17", "HashTable18", "HashTable19", "HashTable20", "HashTable21", "HashTable22", "HashTable23", "HashTable24");

                    b.ToTable("SubFingerprint");
                });

            modelBuilder.Entity("FindSimilarServices.Fingerprinting.SQLiteDb.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Album");

                    b.Property<string>("Artist");

                    b.Property<string>("ISRC");

                    b.Property<int>("ReleaseYear");

                    b.Property<string>("Title");

                    b.Property<double>("TrackLengthSec");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Track");
                });

            modelBuilder.Entity("FindSimilarServices.Fingerprinting.SQLiteDb.Models.SubFingerprint", b =>
                {
                    b.HasOne("FindSimilarServices.Fingerprinting.SQLiteDb.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
